openapi: 3.0.0
info:
  title: laravel-error-tracker-server
  version: 1.0.0
  description: https://github.com/dnj/laravel-error-tracker-server
servers:
  - url: http://127.0.0.1
tags:
  - name: app
  - name: device
  - name: log
paths:
  /api/app/search:
    get:
      tags:
        - app
      summary: search
      parameters:
        - name: title
          in: query
          schema:
            type: string
          example: test
        - name: owner
          in: query
          schema:
            type: integer
          example: '1'
        - name: user
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/app/store:
    post:
      tags:
        - app
      summary: store
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: test
                extra:
                  type: string
                owner:
                  type: string
                '':
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/app/destroy/1:
    delete:
      tags:
        - app
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/app/update/1:
    put:
      tags:
        - app
      summary: update
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: test
                extra:
                  type: string
                owner:
                  type: string
                id:
                  type: integer
                  example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/device/search:
    get:
      tags:
        - device
      summary: search
      parameters:
        - name: title
          in: query
          schema:
            type: string
          example: test
        - name: user
          in: query
          schema:
            type: integer
          example: '1'
        - name: owner
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/device/store:
    post:
      tags:
        - device
      summary: store
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: test
                extra:
                  type: string
                owner:
                  type: string
                '':
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/device/update/1:
    put:
      tags:
        - device
      summary: update
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/device/destroy/1:
    delete:
      tags:
        - device
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/log/search:
    get:
      tags:
        - log
      summary: search
      parameters:
        - name: apps
          in: query
          schema:
            type: string
          example: '[1]'
        - name: devices
          in: query
          schema:
            type: string
          example: '[1]'
        - name: levels
          in: query
          schema:
            type: string
          example: INFO
        - name: message
          in: query
          schema:
            type: string
          example: this message.
        - name: unread
          in: query
          schema:
            type: boolean
          example: 'false'
        - name: user
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/log/store:
    post:
      tags:
        - log
      summary: store
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                app:
                  type: integer
                  example: '1'
                device:
                  type: integer
                  example: '1'
                level:
                  type: string
                  example: INFO
                message:
                  type: string
                  example: this message
                data:
                  type: string
                  example: '[''test'', ''2022-02-02'']'
                read:
                  type: string
                  example: '[''userId'', 1, ''readAt'', 2022-02-02]'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/markAsRead/1:
    put:
      tags:
        - log
      summary: mark as unread
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/log/update/1:
    delete:
      tags:
        - log
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
